//TOYS
export const TOYS_START = "TOYS_START";
export const TOYS_SUCCESS = "TOYS_SUCCESS";
export const TOYS_ERROR = "TOYS_ERROR";
export const TOYS_FINISH = "TOYS_FINISH";

//TOY
export const TOY_START = "TOY_START";
export const TOY_SUCCESS = "TOY_SUCCESS";
export const TOY_ERROR = "TOY_ERROR";
export const TOY_FINISH = "TOY_FINISH";

export const TOY_UPDATE_START = "TOY_UPDATE_START";
export const TOY_UPDATE_SUCCESS = "TOY_UPDATE_SUCCESS";
export const TOY_UPDATE_ERROR = "TOY_UPDATE_ERROR";
export const TOY_UPDATE_FINISH = "TOY_UPDATE_FINISH";

//LOGIN
export const LOGOUT = "LOGOUT";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_FINISH = "LOGIN_FINISH";

export const LOGIN_PAGE_INITIALIZE_START = "LOGIN_PAGE_INITIALIZE_START";
export const LOGIN_PAGE_INITIALIZE_FINISH = "LOGIN_PAGE_INITIALIZE_FINISH";


//TOKEN
export const SET_TOKEN= "SET_TOKEN";

//PROFILE
export const SET_PROFILE = "SET_PROFILE";

/////CATEGORY

// GET CATEGORIES
export const CATEGORIES_START = "CATEGORIES_START";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";
export const CATEGORIES_FINISH = "CATEGORIES_FINISH";

// POST CATEGORY
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const SAVE_NEW_CATEGORY = "SAVE_NEW_CATEGORY";

// GET CATEGORY
export const CATEGORY_START = "CATEGORY_START";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_FINISH = "CATEGORY_FINISH";

// DELETE CATEGORY
export const DELETE_CATEGORY = "DELETE_CATEGORY";

//POST CATEGORY
export const EDIT_CATEGORY_START = "EDIT_CATEGORY_START";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";
export const EDIT_CATEGORY_FINISH = "EDIT_CATEGORY_FINISH";


//TRANSACTION
export const TRANSACTIONS_LIST_START = "TRANSACTIONS_LIST_START";
export const TRANSACTIONS_LIST_SUCCESS = "TRANSACTIONS_LIST_SUCCESS";
export const TRANSACTIONS_LIST_ERROR = "TRANSACTIONS_LIST_ERROR";
export const TRANSACTIONS_LIST_FINISH = "TRANSACTIONS_LIST_FINISH";

export const TRANSACTION_INCOMING_START = "TRANSACTION_INCOMING_START";
export const TRANSACTION_INCOMING_SUCCESS = "TRANSACTION_INCOMING_SUCCESS";
export const TRANSACTION_INCOMING_ERROR = "TRANSACTION_INCOMING_ERROR";
export const TRANSACTION_INCOMING_FINISH = "TRANSACTION_INCOMING_FINISH";

export const TRANSACTION_START = "TRANSACTION_START";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const TRANSACTION_FINISH = "TRANSACTION_FINISH";
