//TOYS
export const TOYS_START = "TOYS_START";
export const TOYS_SUCCESS = "TOYS_SUCCESS";
export const TOYS_ERROR = "TOYS_ERROR";
export const TOYS_FINISH = "TOYS_FINISH";

//TOY
export const TOY_START = "TOY_START";
export const TOY_SUCCESS = "TOY_SUCCESS";
export const TOY_ERROR = "TOY_ERROR";
export const TOY_FINISH = "TOY_FINISH";

export const TOY_UPDATE_START = "TOY_UPDATE_START";
export const TOY_UPDATE_SUCCESS = "TOY_UPDATE_SUCCESS";
export const TOY_UPDATE_ERROR = "TOY_UPDATE_ERROR";
export const TOY_UPDATE_FINISH = "TOY_UPDATE_FINISH";

//LOGIN
export const LOGOUT = "LOGOUT";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_FINISH = "LOGIN_FINISH";

export const LOGIN_PAGE_INITIALIZE_START = "LOGIN_PAGE_INITIALIZE_START";
export const LOGIN_PAGE_INITIALIZE_FINISH = "LOGIN_PAGE_INITIALIZE_FINISH";


//TOKEN
export const SET_TOKEN= "SET_TOKEN";

//PROFILE
export const SET_PROFILE = "SET_PROFILE";

//CATEGORY
export const CATEGORY_START = "CATEGORY_START";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_FINISH = "CATEGORY_FINISH";

//TRANSACTION
export const TRANSACTION_START = "TRANSACTION_START";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const TRANSACTION_FINISH = "TRANSACTION_FINISH";

export const TRANSACTION_INCOMING_START = "TRANSACTION_INCOMING_START";
export const TRANSACTION_INCOMING_SUCCESS = "TRANSACTION_INCOMING_SUCCESS";
export const TRANSACTION_INCOMING_ERROR = "TRANSACTION_INCOMING_ERROR";
export const TRANSACTION_INCOMING_FINISH = "TRANSACTION_INCOMING_FINISH";

export const TRANSACTION_ID_START = "TRANSACTION_ID_START";
export const TRANSACTION_ID_SUCCESS = "TRANSACTION_ID_SUCCESS";
export const TRANSACTION_ID_ERROR = "TRANSACTION_ID_ERROR";
export const TRANSACTION_ID_FINISH = "TRANSACTION_ID_FINISH";
